version: '3.8'
services:
  fun-platform-redis-node1:
    image: redis:6.2.5-alpine3.14
    container_name: fun-platform-redis-node1
    ports:
      - 6380:6379
    command: redis-server --requirepass password123 --appendonly yes
    restart: unless-stopped
    networks:
      - redis
  redis-gui:
    container_name: redis-gui
    hostname: redis-gui
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: label:fun-platform-redis-node1:6379:0:password123
    ports:
      - 8091:8081
    networks:
      - redis
  postgresql:
    container_name: postgres13
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

    volumes:
      -  C:\Users\yulia\Desktop\docker\postgres\data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped 
  
  postgresql_gui:
    container_name:  postgres_gui
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "coldmorning360@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - C:\Users\yulia\Desktop\docker\pgadmin\data:/var/lib/pgadmin

    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge

