

#token
Token:
    ACCESS_TOKEN:
        SECRET: playeresssd
        #15 min 1000*60*15
        TIME: 900000
    REFRESH_TOKEN:
        SECRET: qweasdghtyhq
        # 7 day 1000*60*60*24*7
        TIME: 604800000

#redis 
REDIS_NODE1:
    ENDPOINT: localhost:6380
    PASSWORD: password123
    POOL_SIZE: 100



#postgreSQL
DB_POSTGRESQL:
    HOST: localhost
    PORT: 5432
    DBNAME: fun-platform
    USER: root
    SSLMODEL: disable 
    PASSWORD: root
    TimeZone: Asia/Taipei


